import '../models/product.dart';
import '../constants/assets_manager.dart';

class MockData {
  static final List<Product> mockBooks = [
    Product(
      id: '1',
      title: 'The Art of Design',
      author: 'James Clear',
      description: 'A comprehensive guide to modern design principles.',
      price: 29.99,
      imageUrl: AppAssets.book1,
      category: 'Design',
      rating: 4.8,
    ),
    Product(
      id: '2',
      title: 'Deep Work',
      author: 'Cal Newport',
      description: 'Rules for focused success in a distracted world.',
      price: 24.50,
      imageUrl: AppAssets.book2,
      category: 'Self-Help',
      rating: 4.9,
    ),
    Product(
      id: '3',
      title: 'The Great Gatsby',
      author: 'F. Scott Fitzgerald',
      description: 'A classic novel of the Jazz Age.',
      price: 15.00,
      imageUrl: AppAssets.book3,
      category: 'Fiction',
      rating: 4.5,
    ),
    Product(
      id: '4',
      title: 'Brief History of Time',
      author: 'Stephen Hawking',
      description: 'A landmark in scientific writing.',
      price: 35.00,
      imageUrl: AppAssets.book4,
      category: 'Science',
      rating: 4.7,
    ),
    Product(
      id: '5',
      title: 'Atomic Habits',
      author: 'James Clear',
      description: 'An easy and proven way to build good habits.',
      price: 22.00,
      imageUrl: AppAssets.book5,
      category: 'Self-Help',
      rating: 5.0,
    ),
    Product(
      id: '6',
      title: 'The Alchemist',
      author: 'Paulo Coelho',
      description: 'A global phenomenon about following your dreams.',
      price: 18.99,
      imageUrl: AppAssets.book5,
      category: 'Fiction',
      rating: 4.6,
    ),
    Product(
      id: '7',
      title: 'Design Systems',
      author: 'Alla Kholmatova',
      description: 'A guide to creating and maintaining design systems.',
      price: 32.00,
      imageUrl: AppAssets.book1,
      category: 'Design',
      rating: 4.7,
    ),
    Product(
      id: '8',
      title: 'Sapiens',
      author: 'Yuval Noah Harari',
      description: 'A brief history of humankind.',
      price: 28.00,
      imageUrl: AppAssets.book4,
      category: 'History',
      rating: 4.9,
    ),
  ];
}
